### ISSUE TITLE
bot error

### ISSUE THREAD

**Issue by 1711500065DelvinReynaldi** [naufaljct48/pixelverse#1]
gan mohon di cek bot nya error invalid credentials
terimakasih

**Comment by naufaljct48** [comment]
query nya tdk valid

**Comment by 1711500065DelvinReynaldi** [comment]
udah coba pake query baru lewat console ttep error gan

**Comment by naufaljct48** [comment]
server nya bermasalah gan, barusan check Technical Error

**Comment by 1711500065DelvinReynaldi** [comment]
oke siap gan, terimakasih ya

**Comment by naufaljct48** [comment]
![image](https://github.com/naufaljct48/pixelverse/assets/30202760/a31c2be6-c3df-40b2-89eb-cbc87e30e930)

**Comment by BlackZsh** [comment]
Bro, has this issue been resolved?
